AWSTemplateFormatVersion: 2010-09-09
Description: Create a security group for MySQL access.

# =======================================
# Metadata
# =======================================
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Common Configuration"
        Parameters:
          - PJPrefix
          - Environment
          - ServerKind

# =======================================
# Parameters
# =======================================
Parameters:
  PJPrefix:
    Type: String
    Default: testprefix
    MinLength: 1
    MaxLength: 12
    AllowedPattern: "[a-z0-9]+"
    Description: "Project prefix, consisting of lowercase letters and numbers."
    ConstraintDescription: "Must contain only lowercase letters and numbers."

  Environment:
    Type: String
    Default: dev
    AllowedValues: [ "dev", "stg", "prd" ]
    Description: "Deployment environment (dev, stg, or prd)."

  VPCID:
    Type: AWS::EC2::VPC::Id
    Default: ""
    Description: "VPC ID to associate with the Security Group"

  UseWebSG:
    Type: String
    Default: true
    AllowedValues: [ "true", "false" ]
    Description: "Whether to use EC2 Instance Connect for instance connection."

# =======================================
# Condition
# =======================================
Conditions:
  IsUseWebSG: !Equals [!Ref UseWebSG, "true" ]

# =======================================
# Resources
# =======================================
Resources:

  # -------------------------------------
  # Security Group
  # -------------------------------------
  SecurityGroupForRDS:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Sub "${PJPrefix}-${Environment}-mysqlsg"
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - !If
          - IsUseWebSG
          - IpProtocol: tcp
            FromPort: 3306
            ToPort: 3306
            SourceSecurityGroupId:
              - { "Fn::ImportValue": { "Fn::Sub": "${PJPrefix}-${Environment}-websg" }}
          - !Ref AWS::NoValue
      Tags:
        - Key: Name
          Value: !Sub "${PJPrefix}-${Environment}-mysqlsg"
        - Key: PJName
          Value: !Ref PJPrefix

# =======================================
# Outputs
# =======================================
Outputs:
  SecurityGroupId:
    Value: !Ref SecurityGroupForRDS
    Export:
      Name: !Sub "${PJPrefix}-${Environment}-mysqlsg"
